// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmEBTqjTwU1v7R9NNP__kaH3NqGRlZ8bU',
    appId: '1:145900812346:web:c7c7be10467965d48b9d03',
    messagingSenderId: '145900812346',
    projectId: 'cleanlet-app',
    authDomain: 'cleanlet-app.firebaseapp.com',
    storageBucket: 'cleanlet-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk4zuqL25uKqwQCw6IcxJOL5vAQqih1CE',
    appId: '1:145900812346:android:3d21ab17c097332a8b9d03',
    messagingSenderId: '145900812346',
    projectId: 'cleanlet-app',
    storageBucket: 'cleanlet-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLlndQDjDh_uYcRJcPmuSysUw9o5BSnUo',
    appId: '1:145900812346:ios:6250ba7e4c0366738b9d03',
    messagingSenderId: '145900812346',
    projectId: 'cleanlet-app',
    storageBucket: 'cleanlet-app.appspot.com',
    iosClientId: '145900812346-lq10da4jlj3kvidlgab0usb2u9lbejnc.apps.googleusercontent.com',
    iosBundleId: 'edu.drexel.cleanlet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLlndQDjDh_uYcRJcPmuSysUw9o5BSnUo',
    appId: '1:145900812346:ios:6250ba7e4c0366738b9d03',
    messagingSenderId: '145900812346',
    projectId: 'cleanlet-app',
    storageBucket: 'cleanlet-app.appspot.com',
    iosClientId: '145900812346-lq10da4jlj3kvidlgab0usb2u9lbejnc.apps.googleusercontent.com',
    iosBundleId: 'edu.drexel.cleanlet',
  );
}
